### ISSUE TITLE
Lesson playlist to import from wistia

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#102]
Okay Michelle, here's your list, in order:

https://fitzroyacademy.wistia.com/projects/a88ifqwd53
https://fitzroyacademy.wistia.com/projects/firoc2bicy
https://fitzroyacademy.wistia.com/projects/l64ke0vs70
https://fitzroyacademy.wistia.com/projects/1tij3895e5
https://fitzroyacademy.wistia.com/projects/k092h0u7zg

:)

**Comment by Yuffster** [comment]
Sweet, I'll import these into the demo lesson and make fake teacher accounts.

**Comment by willdayble** [comment]
omg. I'm pretty sure you just try log in via gmail.com and go "password reset", as your backup account is your personal gmail.

pass reset to rememberthisoryousuckforever

**Comment by willdayble** [comment]
closing this, as we have course edit.
