### ISSUE TITLE
Will needs an "if on page X" flag for headers etc

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#112]
For making the "back" button better, I need to do these:

```
If user is on the home page {}
If user is on a course intro {}
If user is on a course view {}
If user is on any static page {}
If user is on any static page {}
```

I feel like we already have this? I am happy to use wacky code full of if/else statements to make the above work.

**Comment by willdayble** [comment]
okay so we already have this, aka:

```
{% if current_section != 'login' %}

{% endif %}
```

Is there a way to use / extend this to do "if section = viewing a course"?

**Comment by Yuffster** [comment]
I made a `url_is` function to go with `url_for`.

So, for example, you could do like:

```.html
{% if url_is('course.view') %}
   Course View!
{% endif %}
```

You can get the things to type into this function from [/api](http://localhost:5000/api).
