### ISSUE TITLE
Make {% if url_is('course.view') %} include the lesson view

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#115]
I am using this to check where the user is in the header:

`{% if url_is('course.view') %}`

It works on the course *intro*, but not the *lesson view*.

Is there a similar thing for like... "user is watching lessons"?

**Comment by willdayble** [comment]
omg it's literally `lesson.view`? HAHA.

Okay, how do I do the codez for "if url is `course.view` OR `lesson.view`" ?

**Comment by willdayble** [comment]
like..

`{% if url_is('course.view' | 'lesson.view' ) %}`

or similar?

**Comment by Yuffster** [comment]
```
{% if url_is('course.view') or url_is('lesson.view' ) %}
```
