### ISSUE TITLE
Helper for arbitrary user settings

### ISSUE THREAD

**Issue by Yuffster** [fitzroyacademy/web-app#121]
Spin-off from #32

@willdayble 
> Can we please add a helper of some kind so that Will can add more "remember this about the user" toggles?
>
>Importantly: This will need to work without a page refresh, for things like "The user has changed their preference for which tabs are open and closed", or similar display things.

**Comment by willdayble** [comment]
We can chat this through if it doesn't make sense...

Some other use cases:

The user clicks a "full screen learning" button, which adds a css class to the <html> tag, and remembers that each time the page is loaded.

It would be awesome to just add like... add to any element `data-fit-remember-key="foo" data-fit-remember-val="bar"` to any click or on-change event...

And then in templates do something like `{% if (remember.foo == "bar")%}` or whatever... just some way to have remembered user settings all over the place that:

* Happen via javascript without page refresh
* Are remembered when the user comes back, even from a different device / session
* Can be used in multiple places in templates

???? Bad explanation sorry.

**Comment by willdayble** [comment]
The example we want:

* Toggle button in the user sidebar that toggles "Breezy view on"
* This adds/removes .pref-'breezy' as a class to `<html>`, e.g. `<html class="fit_dispref-breezy">`

Should add/remove it, and remember it when the person reloads.

All display preferences should be prefaced with `fit_dispref-` and only be attached to `<html>`...

**Comment by willdayble** [comment]
Bump. How we going on this @Yuffster?

**Comment by mkarpicz** [comment]
@willdayble you have one new endpoint
GET /user/settings  - this retrieves all user's custom settings
POST /user/settings - this set new setting data={key: foo, value: bar}

In addition in the context, you have custom_settings dictionary which contains all custom settings of a given user. For anonymous users, we store settings in session.
In addition, we have CUSTOM_SETTINGS_KEYS which defines which keys are allowed. Of course, pair (key, user) has to be unique
