### ISSUE TITLE
Course edit / new course page

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#122]
Probably needs explanation from @willdayble 

However, the weird bits:

* Some sort of image upload - drag and drop would be nice + click to choose a file. This will be a plain image that needs to be auto-resized to 16:9
* Javascripty re-ordering of lessons within the 'Lesson plan' section.
* Everything else is a standard form with 'save'

**Comment by mkarpicz** [comment]
- We assume that only the teacher can edit the course
- What happens if there are already students enrolled in the course with some lessons progress in case a lesson is deleted? This might happen in particular when the course was refreshed after one year.
- Is reordering auto-saved or upon clicking "save"?
- Can a course be in draft mode, when it's not searchable?

**Comment by willdayble** [comment]
> We assume that only the teacher can edit the course

Only teacher(s) assigned to a course can edit courses, and courses may have multiple teachers with full edit access. This will tie into the "institute" management, but for now let's do it simply, if possible.

See here, we will need some jQuery quick lookup on the input (which I have just added and pushed), to assign teachers to a course for edit access.

![image](https://user-images.githubusercontent.com/29651/64134734-7e9eed80-ce24-11e9-8f75-ff87b2604a2a.png)

> What happens if there are already students enrolled in the course with some lessons progress in case a lesson is deleted? This might happen in particular when the course was refreshed after one year.

If a lesson is deleted, for now I'd say there is no undo, and bad luck to the teacher. Data disappears.

We will encourage teachers to refresh courses by duplicating (we haven't build duplicate functionality yet but we will) and changing the year:

![image](https://user-images.githubusercontent.com/29651/64134755-c756a680-ce24-11e9-9d4b-a8039df48398.png)

> Is reordering auto-saved or upon clicking "save"?

My preference is to have EVERYTHING auto-save if possible, and remove save buttons entirely. Can we work towards this where we can?

> Can a course be in draft mode, when it's not searchable?

Good point, I haven't thought of this. Can you add another permission section, just use the 'cost' or 'visibility'  HTML and make it 'Publishing' as a header, with 'Draft' and 'Live' selectors, draft meaning it's only viewable by direct link, and published meaning it goes live.

No need to have special "only logged in teachers can view this lesson", draft can simply mean "only viewable by direct link".

**Comment by willdayble** [comment]
Hey I have improved the HTML for this, hopefully it helps:

![image](https://user-images.githubusercontent.com/29651/64135650-d68e2200-ce2d-11e9-9597-854a961045a5.png)

the `.fit_quicksearch` div now has a search box, and a place for quick search results - `.results`, plus a place for added teachers: `.teachers`, each with example HTML and add/remove buttons.

For now, let's just make it so any teacher can add / remove any other teacher, but at least one teacher needs to be on each course? We can do more complex permissions later?

I haven't chosen a quicksearch / ajax plugin for the functionality, but we might as well choose one that works well for other quick search in the whole site? https://deuxhuithuit.github.io/quicksearch looks good and malleable?

**Comment by willdayble** [comment]
NB: The course edit will need a bunch of if/else all over the place to denote "active" classes and "checked" on the inputs. Eek!

@mkarpicz if you don't want to do this, just give me an example in the tempalte somewhere and I can fill out the rest.

**Comment by mkarpicz** [comment]
- [ ] reload the course edit page after changing course slug
- [ ] instead of success or error alert div use a snackbar widget
- [ ] user can select visibility
- [ ] when selecting Paid course, a user is able to edit the amount
- [ ] a user is able to add and remove tags
- [ ] a user is able to choose a program
- [ ] What you will learn should be WYSIWYG field
- [ ] Changing lessons order actually makes a difference 
- [ ] On a lesson display calculated the time of segments
- [ ] Make course edit templates more reusable

**Comment by mkarpicz** [comment]
@willdayble what should be the action for "Save" if we're using autosave all over the place? In addition, I think that we should add some snackbar notification the saving changes was (or not) successful.

In addition how about adding some snackbar with notifications all over the place?

**Comment by willdayble** [comment]
Good questions, let's chat this through (tonight), @mkarpicz?

**Comment by willdayble** [comment]
For html edit: https://github.com/yabwe/medium-editor

**Comment by mkarpicz** [comment]
@willdayble It would be good to add some fancy button "edit course" somewhere, so we can close this ticket. Also, there is one thing left on my side: adding and removing tags. How do you want to use them at this stage of the project?

**Comment by mkarpicz** [comment]
- [ ] Put if a teacher so Will can add HTML magic.
