### ISSUE TITLE
Add another field for course.length_short to edit

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#148]
Here's a screengrab of the new bit in the template...

We need to split the "course workload" into two parts:

`workload.title` = e.g. 32 hours, 12 weeks.
`workload.subtitle` = e.g. 4 hours study per week on average, best done with friends!

Note, this is different to `course.lessons|length` which is the total number of lessons...

The above is free text for teachers to enter their own guess at standard workload. :)

![image](https://user-images.githubusercontent.com/29651/65474147-193b9b00-debe-11e9-8323-732c2b507d68.png)

**Comment by willdayble** [comment]
while I'm thinking about it...

Above, the `18+ resources` htmHTML should just be the `|length` of all the resources in all of the lessons in the  course. 

We'll use the same if/elses on free-ness for the second enrol button.

**Comment by mkarpicz** [comment]
Why not add only course length, that is this course will last for X weeks. Then we can calculate how much effort is needed per one week of studying?
