### ISSUE TITLE
FAQ editor doesn't seem to "add" until page refresh

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#152]
See `http://localhost:5000/course/fitzroy-academy/lessons/2/edit`

When the user clicks the "add" button, it doesn't appear to add the item. It should either:

1. Do a page refresh
2. Add the new FAQ html above the form

My preference for option 2!

**Comment by mkarpicz** [comment]
The kind of "typo" bugs... Before pushing code I've change list id in one place and forgot about other...
