### ISSUE TITLE
Make a "preserve paragraphs" output for templates

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#155]
See _lesson.html at ~line 210:

```
{% if resource.description %}
  <a class="explain">
      {{ resource.description }}
  </a>
{% endif %}
```

... this displays as

```
  <a class="explain">
      content goes here
and doesn't preserve
paragraphs

  </a>
```

Can we please do this (or something similar)?:

```
{% if resource.description %}
  <a class="explain">
      {{ resource.description|paragraph }}
  </a>
{% endif %}
```
should display as:

```
  <a class="explain">
      <p>content goes here</p>
      <p>and doesn't preserve</p>
      <p>paragraphs</p>
  </a>
```

e.g. just change newlines into paragraphs?

**Comment by mkarpicz** [comment]
So, in other words, you would like to have wysiwyg editor for description?

**Comment by willdayble** [comment]
That is one way to do it. Actually, haha, yes, do that!

I can just make the wysiwyg for that block have a lot fewer editing controls with JS and it will work fine. Yay!
