### ISSUE TITLE
Placeholders don't show up in course edit

### ISSUE THREAD

**Issue by Yuffster** [fitzroyacademy/web-app#163]
Here the content is set to "None" by lines like this in the template:

```
{{ course.workload_summary|default("") }}
```

![](https://user-images.githubusercontent.com/13204/67422650-e5c55c80-f5a0-11e9-9f9c-802d7d821ce9.png)

**Comment by mkarpicz** [comment]
Yes, I've added an empty string as a default value for some columns in the course model.
