### ISSUE TITLE
Can't edit intro lesson?

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#170]
see http://localhost:5000/course/fitzroy-academy/edit#

![image](https://user-images.githubusercontent.com/29651/67825317-0bacad00-fb1d-11e9-967e-3ac580844365.png)

The introduction 'edit' doesn't work, for either courses or lessons. There is a modal called `_add_intro.html` that can be used for this purpose.

**Note:** I've moved the modals for course editing into `course_edit.html`, i.e:

```
<!-- adding things -->
{% include 'partials/modal/_add_lesson.html' %}
{% include 'partials/modal/_add_lesson_fitz.html' %}
{% include 'partials/modal/_add_intro.html' %}
```

... if you need any of these modals for other edit pages (i.e. I'm guessing you'll want to use `add_intro` for within the lesson edit), add them in! :)

**Comment by mkarpicz** [comment]
@willdayble so far adding and editing lessons and segments was made in a separate view. Now, you would like to have it in modals, yes?
