### ISSUE TITLE
Barrier and visibility on lessons and surveys

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#177]
Notes to talk through:

Segment barriers:

- [ ] **Normal** Can be skipped
- [ ] **Soft barrier** Only this segment must be completed to continue (but not previous)
- [ ] **Hard barrier** This and _every prior segment_ must be completed to continue
- [ ] **Hidden** Not shown to students, visible only to teachers

???

**Comment by willdayble** [comment]
CRAP I just realised we have another use case @mkarpicz, sorry!

There is the idea of "hard and soft" barriers within the course, but we haven't thought about it within lessons.

* I.e. "Complete this segment before doing the rest of the LESSON"
* Versus: "Complete this segment before doing the rest of the COURSE"

They are different. Argh! Let's talk this through next catchup?

**Comment by willdayble** [comment]
Okay I keep realising I'm screwing this up.

I just realised there will be **another** form of 'barrier' in the future:

- [ ] Payment barrier. I.e. "user can only watch this / subsequent segments after paying for the course"

This would be important for giving people a 'taster' of a course. I guess we could get around this easily by just having the intro video always visible no matter what? Then we don't have to rework the entire enrolment / barrier system further?

**Comment by willdayble** [comment]
OH GOD ANOTHER:

- [ ] **Must login to continue:** User can watch anonymously up until a certain segment, after which they must make an account to continue.

Let's leave this until I have made up my mind completely

**Comment by Yuffster** [comment]
Coding these things is how you discover what we want to do. :D
