### ISSUE TITLE
Image upload works for courses, but not elsewhere

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#182]
See this commit, I have tried to make the lessons image uploader HTML same as on courses (which works great), but it doesn't work:

https://github.com/fitzroyacademy/web-app/commit/97114e902b928807cd4fc81dcadcd57a25da4d62

Note, we also need image upload to work in a few other places:

- [x] User edit (avatar)
- [x] Institute pages (logo)
- [x] Lesson edit

:)

**Comment by mkarpicz** [comment]
I've fixed this for institute pages and lesson edit in the commit `26190f2` (branch `institute-page`).
