### ISSUE TITLE
Resource links are buggy

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#184]
Not entirely sure what's happening here:

On the course view:

- [ ] `resource.type` doesn't seem to be coming through properly, I can see something weird like `ResourceTypeEnum.google_sheet` in the class attr.
- [ ] We should be displaying the human readable name, I'm not sure what the template tag is?

**Comment by mkarpicz** [comment]
We should use:
- `resource.type.name` for human-readable name
- `resource.type.value` for underlying value
