### ISSUE TITLE
_nav_lesson.html isn't showing complete-ness or locked-ness yet

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#186]
The anchor within `{% for segment in lesson.segments %}` needs to have a few more classes, depending on its state:

- [ ] Completed lessons need a `.complete` class if completed
- [ ] Locked lessons need a `.locked` class if locked

_NB: We haven't figured out what to do with redirecting users in "locked" lessons yet, I will make a template._

**Comment by willdayble** [comment]
I have added a static template to be used for a 'locked' segment:

[http://localhost:5000/surveys/locked](http://localhost:5000/surveys/locked)

Note there is two `<p>`s, one for soft lock and one for hard lock.

**Comment by mkarpicz** [comment]
@willdayble correct me if I'm wrong, first we need tracking lesson progress before we can determine if the given segment is locked, right?

**Comment by Yuffster** [comment]
We track lesson progress, I'll add the classes.

**Comment by Yuffster** [comment]
@mkarpicz I'm going to kick this one back to you.  I've added a stubbed out `Segment.prereqs_met`  method that needs integration with the `SegmentPermissionEnum` you set up.

See 82b8ec6b361cba3d57e4c136499b1d84f6277243/datamodels.py for all the good stuff I've added.  Segments now have `.previous` and `.next` properties to help with this.

Whether a barrier should exist:

https://github.com/fitzroyacademy/web-app/blob/82b8ec6b361cba3d57e4c136499b1d84f6277243/datamodels.py#L847-L850

Whether the barrier conditions have been met:

https://github.com/fitzroyacademy/web-app/blob/82b8ec6b361cba3d57e4c136499b1d84f6277243/datamodels.py#L887-L8890

Please add examples of each barrier type to stubs.
