### ISSUE TITLE
Standardise and fix WYSIWYG editors

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#191]
Looking at http://fitz-dev.com:5000/course/fitzroy-academy/lessons/2/edit

See `_lesson.html`, it seems to have ugly `<script>` tags down the bottom of the file doing the wysiwyg stuff, should this all be in fit.js and whatnot?

This is probably a reason to check out how we're doing them all.

### Maybe we need some standards:

1. `data-fit-wysiwyg-full` = full wysiwyg text-editor with headers, links, quotes, image upload etc
2. `data-fit-wysiwyg-lite` = Only bold/italic + links (no headers, quotes, etc)
3. `data-fit-wysiwyg-min` = only carriage returns

I think that's it? We should probably chat this through I'm guessing lol.

**Comment by willdayble** [comment]
Or alternatively, separate for attr for options?

**Comment by Yuffster** [comment]
Alright, fresh template macro.

`wysiwyg(input_name, content, toolbar_styles)`

Everything but `input_name` is optional.

Example:

```
{{ wysiwyg('course_summary', course.summary_html, ['bold', 'italic']) }}
```

You have to wrap things in an empty form in course edit though until we can untangle all the gnarly autosave code.

```
<form>
    {{ wysiwyg('course_summary', course.summary_html, ['bold', 'italic']) }}
</form>
```
