### ISSUE TITLE
Block  .DS_Store files from git?

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#74]
I am bad at this lol, can we git ignore `.DS_Store` files so I'm not crapping all over the folder structure?

**Comment by quercy** [comment]
[Should already be ignored](https://github.com/fitzroyacademy/web-app/blob/master/.gitignore#L1) - is it showing up in your commits?

**Comment by willdayble** [comment]
apparently? I'll check with you next time we chat, soz for the ticket hah.
