### ISSUE TITLE
a python version of var_dump for front-end dev

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#81]
I'd like to know what variables I can safely use in for loops:

E.g, within the loop: {% for lesson in course.lessons %}

What {{ lesson.title }} type stuff can I use? {{ lesson.blah }} and {{ lesson.bloop }} ?

**Comment by Yuffster** [comment]
What if you could add `.json` to the end of a URL and see a dump of all the template variables in dev mode? 🤔

**Comment by willdayble** [comment]
yeah whatever is easiest for you works for me! :)

**Comment by Yuffster** [comment]
I made a var dump template in `partials/_debug_template_vars.html` and just stuck it on the bottom of the layout for now. 

![image](https://user-images.githubusercontent.com/13204/61558906-5acf4600-aa36-11e9-9fce-4e075ba0c62b.png)
