### ISSUE TITLE
URL checking helper?

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#91]
See `partials/static_menus/_about.html` for where this will be used

... each of these links needs an "if I am on this slug, show active".

ALSO: Could we do this with a slug-checking helper in URLs, for subfolders?

Psuedocode for /about/blah
`{% if url_check ='about/blah' %}`

Or maybe...
`{% if url_check[0] ='about' %}`

Or ALSO...
`{% if url_check[1] ='blah' %}`

... all would return true?

**Comment by Yuffster** [comment]
Flask has some cool [URL Building helpers](https://flask.palletsprojects.com/en/1.0.x/quickstart/#url-building) baked in; this is something we can do a lot easier once we break out the routes and organize them a bit (#58).
